version: "3.5"

services:
  composition:
    container_name: "phone_catalog-nginx"
    restart: "unless-stopped"
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    #    Can be used to get debug log of Nginx
    # command: [nginx-debug, '-g', 'daemon off;']

  # phone_catalog-ui:
  #   image: repository.diacare-soft.ru/docker/phone_catalog/phone_catalog-ui:${IMAGE_UI}
  #   restart: unless-stopped
  #   container_name: phone_catalog-ui
  #   ports:
  #     - ${FRONT_PORT}
  #   volumes:
  #     - ./logs/nginx/front:/var/log/nginx
  #   environment:
  #     - LOCLANG=ru

  keycloak:
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    container_name: phone_catalog-keycloak
    command: start-dev --http-port=8082 --db-url-host postgres --db-username postgres --db-password postgres --db=postgres --log-level=TRACE
    depends_on:
      - postgres
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=phone_catalog-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - 8082:8082

  phone_catalog-back:
    image: back/image
    restart: unless-stopped
    container_name: phone_catalog-back
    depends_on:
      - postgres
    ports:
      - ${BACK_PORT}:${BACK_PORT}
      - 9229:9229
    environment:
      - DB_URL=${DB_URL}
      - LC_COLLATE=ru_RU.utf8
      - LC_MESSAGES=ru_RU
      - REALM_PUBLIC_KEY=${REALM_PUBLIC_KEY}
      - REALM_SECRET=${REALM_SECRET}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - DISABLE_AUTH=${DISABLE_AUTH}
      - REALM=${REALM}
    volumes:
      - ./logs/back:/home/app/logs
    command: node --trace-warnings --inspect=0.0.0.0:9229 src/app.js
    # working_dir: /home/app


  phone_catalog-front:
    image: front/image
    restart: unless-stopped
    container_name: phone_catalog-front
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - DB_URL=${DB_URL}
      - LC_COLLATE=ru_RU.utf8
      - LC_MESSAGES=ru_RU
      - REALM_PUBLIC_KEY=${REALM_PUBLIC_KEY}
      - REALM_SECRET=${REALM_SECRET}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}
      - DISABLE_AUTH=${DISABLE_AUTH}
      - REALM=${REALM}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PORT=${VITE_PORT}
    volumes:
      - ./logs/back:/home/app/logs
    command: npm run host
    # working_dir: /home/app/ui


  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: phone_catalog-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
      - LANGUAGE=ru_RU
      - LC_ALL=ru_RU.UTF-8
      - LC_COLLATE=ru_RU.UTF-8
      - LC_CTYPE=ru_RU.UTF-8
      - LANG=ru_RU.UTF-8
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db_init:/db_init
    command: /bin/bash -c 'echo "ru_RU.UTF-8 UTF-8\nen_US.UTF-8 UTF-8" | tee -a /etc/locale.gen; echo 'LANG="ru_RU.UTF-8"'>/etc/default/locale; dpkg-reconfigure --frontend=noninteractive locales; update-locale LC_ALL=ru_RU.UTF-8; /usr/local/bin/docker-entrypoint.sh postgres; psql -U postgres -d database -a -f /docker-entrypoint-initdb.d/init.sql'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"

  memcached:
    image:          memcached:alpine
    restart:        unless-stopped
    container_name: memcached
    ports:
      - ${MEMCACHED_PORT}:11211
    labels:
      - "traefik.enable=false"
    command: ["-m", "64m"]
